// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtoY_AMWrIAfaZDcGw0v3qWrRStM1O21E',
    appId: '1:835199128980:web:9d131f886114eaf954eb81',
    messagingSenderId: '835199128980',
    projectId: 'smart-school-bus-8e7d1',
    authDomain: 'smart-school-bus-8e7d1.firebaseapp.com',
    databaseURL: 'https://smart-school-bus-8e7d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-school-bus-8e7d1.firebasestorage.app',
    measurementId: 'G-QLP5DNG3B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6lgCu1v07skVYLWjqZUUAAmHa_wdap1U',
    appId: '1:835199128980:android:c43ecf57d49af86e54eb81',
    messagingSenderId: '835199128980',
    projectId: 'smart-school-bus-8e7d1',
    databaseURL: 'https://smart-school-bus-8e7d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-school-bus-8e7d1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbmQ198QdxukObkDQ_A7hMTT9OgXLnQqA',
    appId: '1:835199128980:ios:5f268b3866e4d45754eb81',
    messagingSenderId: '835199128980',
    projectId: 'smart-school-bus-8e7d1',
    databaseURL: 'https://smart-school-bus-8e7d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-school-bus-8e7d1.firebasestorage.app',
    iosBundleId: 'com.schoolbussafe.schoolbusSafe',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbmQ198QdxukObkDQ_A7hMTT9OgXLnQqA',
    appId: '1:835199128980:ios:5f268b3866e4d45754eb81',
    messagingSenderId: '835199128980',
    projectId: 'smart-school-bus-8e7d1',
    databaseURL: 'https://smart-school-bus-8e7d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-school-bus-8e7d1.firebasestorage.app',
    iosBundleId: 'com.schoolbussafe.schoolbusSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtoY_AMWrIAfaZDcGw0v3qWrRStM1O21E',
    appId: '1:835199128980:web:65186e879a68139a54eb81',
    messagingSenderId: '835199128980',
    projectId: 'smart-school-bus-8e7d1',
    authDomain: 'smart-school-bus-8e7d1.firebaseapp.com',
    databaseURL: 'https://smart-school-bus-8e7d1-default-rtdb.firebaseio.com',
    storageBucket: 'smart-school-bus-8e7d1.firebasestorage.app',
    measurementId: 'G-QMRSG43PXG',
  );
}
